require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PoemsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Poem. As you add validations to Poem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:poem)
  }

  let(:invalid_attributes) {
    {title: '', text: ''}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PoemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all posts as @posts" do
      poem = Poem.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:poems)).to eq([poem])
    end
  end

  describe "GET show" do
    it "assigns the requested poem as @poem" do
      poem = Poem.create! valid_attributes
      get :show, {:id => poem.to_param}, valid_session
      expect(assigns(:poem)).to eq(poem)
    end
  end

  describe "GET new" do
    it "assigns a new poem as @poem" do
      get :new, {}, valid_session
      expect(assigns(:poem)).to be_a_new(Poem)
    end
  end

  describe "GET edit" do
    it "assigns the requested poem as @poem" do
      poem = Poem.create! valid_attributes
      get :edit, {:id => poem.to_param}, valid_session
      expect(assigns(:poem)).to eq(poem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Poem" do
        expect {
          post :create, {:poem => valid_attributes}, valid_session
        }.to change(Poem, :count).by(1)
      end

      it "assigns a newly created poem as @poem" do
        post :create, {:poem => valid_attributes}, valid_session
        expect(assigns(:poem)).to be_a(Poem)
        expect(assigns(:poem)).to be_persisted
      end

      it "redirects to the created poem" do
        post :create, {:poem => valid_attributes}, valid_session
        expect(response).to redirect_to(Poem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved poem as @poem" do
        post :create, {:poem => invalid_attributes}, valid_session
        expect(assigns(:poem)).to be_a_new(Poem)
      end

      it "re-renders the 'new' template" do
        post :create, {:poem => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        attributes_for(:poem, title: 'new')
      }

      it "updates the requested poem" do
        poem = Poem.create! valid_attributes
        put :update, {:id => poem.to_param, :poem => new_attributes}, valid_session
        poem.reload
        expect(poem.title).to eq 'new'
      end

      it "assigns the requested poem as @poem" do
        poem = Poem.create! valid_attributes
        put :update, {:id => poem.to_param, :poem => valid_attributes}, valid_session
        expect(assigns(:poem)).to eq(poem)
      end

      it "redirects to the poem" do
        poem = Poem.create! valid_attributes
        put :update, {:id => poem.to_param, :poem => valid_attributes}, valid_session
        expect(response).to redirect_to(poem)
      end
    end

    describe "with invalid params" do
      it "assigns the poem as @poem" do
        poem = Poem.create! valid_attributes
        put :update, {:id => poem.to_param, :poem => invalid_attributes}, valid_session
        expect(assigns(:poem)).to eq(poem)
      end

      it "re-renders the 'edit' template" do
        poem = Poem.create! valid_attributes
        put :update, {:id => poem.to_param, :poem => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested poem" do
      poem = Poem.create! valid_attributes
      expect {
        delete :destroy, {:id => poem.to_param}, valid_session
      }.to change(Poem, :count).by(-1)
    end

    it "redirects to the posts list" do
      poem = Poem.create! valid_attributes
      delete :destroy, {:id => poem.to_param}, valid_session
      expect(response).to redirect_to(poems_url)
    end
  end

end
